# Generated by Django 3.1.4 on 2021-01-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.BigIntegerField(blank=True, max_length=100, null=True),
        ),
    ]
