# Generated by Django 3.1.4 on 2021-01-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_user_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_work',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
